In [25]:
import numpy as np 
import math


l1=[10,20,30,40,50]
e1=5

for i in range(len(l1)):
    add=l1[i]+5
print(l1)


[10, 20, 30, 40, 50]


In [13]:
n1=np.array(l1)
n2=n1+e1
print(n2)
len(l1)

[15 25 35 45 55]


5

In [34]:

l1=[2,4,6,8]
l2=[3,6,9,12]
n1=np.array(l1)
n2=np.array(l2)
l3=n1+n2
l4=n1-n2
print(l3)
print(l4)
l5=n1*n2
l6=n1/n2
print(l5)
print(l6)
l7=n1%n2
print(l7)
l8=n1**n2
print(l8)
l9=n1//n2
print(l9)

[ 5 10 15 20]
[-1 -2 -3 -4]
[ 6 24 54 96]
[0.66666667 0.66666667 0.66666667 0.66666667]
[2 4 6 8]
[          8        4096    10077696 68719476736]
[0 0 0 0]


In [33]:
l3=[]
l4=[]
for i in range(len(l1)):
    add=l1[i]+l2[i]
    sub=l1[i]-l2[i]
    l3.append(add)
    l4.append(sub)

print(l3)
print(l4)


[5, 10, 15, 20]
[-1, -2, -3, -4]


In [35]:
n1.dtype

dtype('int64')

In [36]:
n1.size

4

In [37]:
n1.ndim

1

In [38]:
n1.shape

(4,)

In [39]:
n1.itemsize


8

In [ ]:
l5=[[1,2,3,4,5],[9,2,3,4,5]]
m=np.array(l5)
print(m)

[[1 2 3 4 5]
 [9 2 3 4 5]]


In [62]:
q=np.array([1,2,3,4,5,6])
print(q)
i=0
while i < q.size:
    print(q[i])
    i+=1
    


[1 2 3 4 5 6]
1
2
3
4
5
6


In [71]:

salary=np.array([130200,20000,30000,400000,500000])
tax=salary*0.10
increment=salary*0.20
gs_sal=salary+increment-tax
print(tax)
print(tax.sum())
print(salary.sum())
print(np.sum(tax))
print(gs_sal)

[13020.  2000.  3000. 40000. 50000.]
108020.0
1080200
108020.0
[143220.  22000.  33000. 440000. 550000.]


In [72]:
ta=salary*0.5
da=salary*0.10
gs=salary+ta+da
print(gs)


[208320.  32000.  48000. 640000. 800000.]
