In [101]:
import numpy as np

In [102]:
arr1=np.zeros(10)
print(arr1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [103]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [104]:
arr3=np.zeros((3,3,3))
arr3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [105]:
arr4=np.zeros((2,3,3,2))
arr4

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [106]:
n1=np.array([10,20,30,40])
n2=np.zeros(4)
n2[1]=10
print(n1+n2)
print(n2)

[10. 30. 30. 40.]
[ 0. 10.  0.  0.]


In [107]:
arr2=np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
arr2=np.full((2,2),7)
print(arr2)

[[7 7]
 [7 7]]


In [109]:
arr2=np.full((2,2,2),7)
print(arr2)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [110]:
arr2=np.full((2,2,3,3),7)
print(arr2)

[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]]


In [111]:
arr2=np.full(2,2)
print(arr2)

[2 2]


In [112]:
arr2=np.eye(2)
arr2

array([[1., 0.],
       [0., 1.]])

In [113]:
arr2=np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
arr2.flatten()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [115]:
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [116]:
arr1.shape


(10,)

In [117]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
arr1.reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [119]:
arr1=np.eye(4)

In [120]:
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
arr1.reshape(2,4,2)

array([[[1., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.]]])

In [122]:
arr1.reshape(2,2,2,2)

array([[[[1., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]]],


       [[[0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 1.]]]])

In [123]:
arr3=np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
arr1=np.linspace(1,6,20)
arr1

array([1.        , 1.26315789, 1.52631579, 1.78947368, 2.05263158,
       2.31578947, 2.57894737, 2.84210526, 3.10526316, 3.36842105,
       3.63157895, 3.89473684, 4.15789474, 4.42105263, 4.68421053,
       4.94736842, 5.21052632, 5.47368421, 5.73684211, 6.        ])

In [125]:
arr1=np.random.randint(1,100,3)
print(arr1)

[10 50 39]


In [126]:
arr1=np.random.random(20)
arr1

array([0.37678613, 0.1953458 , 0.95492044, 0.70282601, 0.63736288,
       0.67269103, 0.02532494, 0.24484667, 0.87814785, 0.06713419,
       0.00149625, 0.37996747, 0.34367126, 0.61085797, 0.41026574,
       0.20484415, 0.0228365 , 0.95597947, 0.20641889, 0.98907325])

In [146]:
arr1=np.empty(4)
arr1

array([1.37929726e-312, 6.79038653e-313, 1.67637668e-312, 1.54905693e-312])

In [128]:
n1=np.array([10,20,30,40,50])
arr1=np.repeat(n1,2)
print(arr1)

[10 10 20 20 30 30 40 40 50 50]


In [129]:
arr1=np.array(['ajay','vijay','arun','hardik','raj'])
arr2=np.array(['sharma','gupta','singh','mishra','soni'])

In [130]:
print(np.char.upper(arr1 +" "+ arr2))

['AJAY SHARMA' 'VIJAY GUPTA' 'ARUN SINGH' 'HARDIK MISHRA' 'RAJ SONI']


In [131]:
print(np.char.upper(arr2))

['SHARMA' 'GUPTA' 'SINGH' 'MISHRA' 'SONI']


In [132]:
print(np.char.capitalize(arr1))

['Ajay' 'Vijay' 'Arun' 'Hardik' 'Raj']


In [133]:
print(np.char.title(arr1))

['Ajay' 'Vijay' 'Arun' 'Hardik' 'Raj']


In [134]:
n3=np.array(['hello world guys','hell world guys '])
print(np.char.title(n3))

['Hello World Guys' 'Hell World Guys ']


In [135]:
np.char.strip(n3)

array(['hello world guys', 'hell world guys'], dtype='<U16')

In [136]:
np.char.islower(n3)

array([ True,  True])

In [137]:
np.char.isupper(n3)

array([False, False])

In [138]:
np.char.isalpha(n3)

array([False, False])

In [139]:
np.char.isspace(n3)

array([False, False])

In [140]:
np.char.istitle(n3)

array([False, False])

In [141]:
np.char.isnumeric(n3)

array([False, False])

In [142]:
np.char.isdigit(n3)

array([False, False])

In [143]:
n=np.array(['1','4','2','3','6'])
np.char.isdigit(n)

array([ True,  True,  True,  True,  True])

In [144]:
n=np.array(['1','4','2','3','6'])
np.char.multiply(n,12)

array(['111111111111', '444444444444', '222222222222', '333333333333',
       '666666666666'], dtype='<U12')