In [1]:
import numpy as np

In [2]:
arr1=np.zeros(10)
print(arr1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr3=np.zeros((3,3,3))
arr3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
arr4=np.zeros((2,3,3,2))
arr4

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [12]:
n1=np.array([10,20,30,40])
n2=np.zeros(4)
n2[1]=10
print(n1+n2)
print(n2)

[10. 30. 30. 40.]
[ 0. 10.  0.  0.]


In [13]:
arr2=np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr2=np.full((2,2),7)
print(arr2)

[[7 7]
 [7 7]]


In [15]:
arr2=np.full((2,2,2),7)
print(arr2)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [16]:
arr2=np.full((2,2,3,3),7)
print(arr2)

[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]]


In [17]:
arr2=np.full(2,2)
print(arr2)

[2 2]


In [ ]:
arr2=np.eye(2)
arr2

array([[1., 0.],
       [0., 1.]])

In [20]:
arr2=np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
arr2.flatten()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [22]:
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
arr1.shape


(10,)

In [32]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
arr1.reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
arr1=np.eye(4)

In [34]:
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
arr1.reshape(2,4,2)

array([[[1., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.]]])

In [37]:
arr1.reshape(2,2,2,2)

array([[[[1., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]]],


       [[[0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 1.]]]])

In [41]:
arr3=np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr1=np.linspace(1,6,20)
arr1

array([1.        , 1.26315789, 1.52631579, 1.78947368, 2.05263158,
       2.31578947, 2.57894737, 2.84210526, 3.10526316, 3.36842105,
       3.63157895, 3.89473684, 4.15789474, 4.42105263, 4.68421053,
       4.94736842, 5.21052632, 5.47368421, 5.73684211, 6.        ])

In [67]:
arr1=np.random.randint(1,100,3)
print(arr1)

[10 13 39]


In [69]:
arr1=np.random.random(20)
arr1

array([0.96023002, 0.58942206, 0.98066513, 0.37691943, 0.46662122,
       0.97629162, 0.54952483, 0.54812279, 0.75882204, 0.15367156,
       0.70294808, 0.73034334, 0.93836424, 0.91198847, 0.98773362,
       0.41737022, 0.71564292, 0.65246636, 0.10769765, 0.77215031])

In [70]:
arr1=np.empty(5)
arr1

array([0.00000000e+000, 1.57858359e-311, 1.57858359e-311, 1.57858359e-311,
       0.00000000e+000])

In [71]:
n1=np.array([10,20,30,40,50])
arr1=np.repeat(n1,2)
print(arr1)

[10 10 20 20 30 30 40 40 50 50]


In [73]:
arr1=np.array(['ajay','vijay','arun','hardik','raj'])
arr2=np.array(['sharma','gupta','singh','mishra','soni'])

In [79]:
print(np.char.upper(arr1 +" "+ arr2))

['AJAY SHARMA' 'VIJAY GUPTA' 'ARUN SINGH' 'HARDIK MISHRA' 'RAJ SONI']


In [75]:
print(np.char.upper(arr2))

['SHARMA' 'GUPTA' 'SINGH' 'MISHRA' 'SONI']


In [81]:
print(np.char.capitalize(arr1))

['Ajay' 'Vijay' 'Arun' 'Hardik' 'Raj']


In [83]:
print(np.char.title(arr1))

['Ajay' 'Vijay' 'Arun' 'Hardik' 'Raj']


In [85]:
n3=np.array(['hello world guys','hell world guys '])
print(np.char.title(n3))

['Hello World Guys' 'Hell World Guys ']


In [87]:
np.char.strip(n3)

array(['hello world guys', 'hell world guys'], dtype='<U16')

In [88]:
np.char.islower(n3)

array([ True,  True])

In [89]:
np.char.isupper(n3)

array([False, False])

In [90]:
np.char.isalpha(n3)

array([False, False])

In [91]:
np.char.isspace(n3)

array([False, False])

In [92]:
np.char.istitle(n3)

array([False, False])

In [93]:
np.char.isnumeric(n3)

array([False, False])

In [94]:
np.char.isdigit(n3)

array([False, False])

In [96]:
n=np.array(['1','4','2','3','6'])
np.char.isdigit(n)

array([ True,  True,  True,  True,  True])

In [100]:
n=np.array(['1','4','2','3','6'])
np.char.multiply(n,12)

array(['111111111111', '444444444444', '222222222222', '333333333333',
       '666666666666'], dtype='<U12')