In [2]:
import numpy as np 

In [3]:
l4=[
    [
    [ [10,20],[30,40]],
    [ [11,21],[31,41]]
    ],
    [
    [[90,20],[20,11]],
    [[20,50],[40,60]]
    ]
]

In [4]:
ar4=np.array(l4) 

In [5]:
print(ar4.shape)

(2, 2, 2, 2)


In [6]:
print(ar4.ndim)

4


In [7]:
ar4[0,0,0,0]

np.int64(10)

In [8]:
ar4[0,0,1,0]

np.int64(30)

In [9]:
ar4[0,1,0,0]

np.int64(11)

In [10]:
ar4

array([[[[10, 20],
         [30, 40]],

        [[11, 21],
         [31, 41]]],


       [[[90, 20],
         [20, 11]],

        [[20, 50],
         [40, 60]]]])

In [11]:
ar4[0,0,1,0]

np.int64(30)

In [12]:
ar4[1,0,0,0]

np.int64(90)

In [13]:
ar4[:2,:2,:1,:1]

array([[[[10]],

        [[11]]],


       [[[90]],

        [[20]]]])

In [14]:
ar4[:2,:2,:1,:1].ndim

4

In [15]:
ar4[:2,:2,:1,:1].shape

(2, 2, 1, 1)

In [16]:
ar4[:2,:2,:1,:1].mean()

np.float64(32.75)

In [25]:
for i in range(ar4.shape[0]):
    for j in range(ar4.shape[1]):
        for k in range(ar4.shape[2]):
            for l in range(ar4.shape[3]):
                print(ar4[i,j,k,l],end=" ")

10 20 30 40 11 21 31 41 90 20 20 11 20 50 40 60 

In [31]:
ar4

array([[[[10, 20],
         [30, 40]],

        [[11, 21],
         [31, 41]]],


       [[[90, 20],
         [20, 11]],

        [[20, 50],
         [40, 60]]]])

In [ ]:
for i in range(ar4.shape[0]):
    # for j in i:
    print(a)
     

[[[[10 20]
   [30 40]]

  [[11 21]
   [31 41]]]


 [[[90 20]
   [20 11]]

  [[20 50]
   [40 60]]]]
[[[[10 20]
   [30 40]]

  [[11 21]
   [31 41]]]


 [[[90 20]
   [20 11]]

  [[20 50]
   [40 60]]]]


In [53]:
ar4

array([[[[10, 20],
         [30, 40]],

        [[11, 21],
         [31, 41]]],


       [[[90, 20],
         [20, 11]],

        [[20, 50],
         [40, 60]]]])

In [59]:
ar4[:2,:2,0:2,1:2]

array([[[[20],
         [40]],

        [[21],
         [41]]],


       [[[20],
         [11]],

        [[50],
         [60]]]])

In [60]:
ar4[:1,:2,:2,:2]

array([[[[10, 20],
         [30, 40]],

        [[11, 21],
         [31, 41]]]])

In [63]:
m=ar4[:1]
q=ar4[:2]
a=ar4[:2]
b=ar4[:2]

for i in m:
    for j in q:
        for k in a:
            for l in b:
                print(ar4[i,j,k,l])

IndexError: index 10 is out of bounds for axis 0 with size 2

In [65]:
for i in ar4:
    for j in i:
        for k in j:
            for l in k:
                print(l)

10
20
30
40
11
21
31
41
90
20
20
11
20
50
40
60
