In [3]:
import numpy as np 

In [4]:
ar1=np.array([10,20,30,40,50])
print(ar1.ndim)
print(ar1.shape)
print(ar1.size)
print(ar1.itemsize)


1
(5,)
5
8


In [5]:
#aggregate functions 
# max()
# min()
# mean()
# median()
# sum()
# var()
# std()

In [6]:
print("max",np.max(ar1))

max 50


In [7]:
print("mean",np.mean(ar1))

mean 30.0


In [8]:
print("median",np.median(ar1))

median 30.0


In [9]:
print("sum",np.sum(ar1))

sum 150


In [134]:
print("sum",np.shape(ar1))

sum (5,)


In [11]:
print("standard division",np.std(ar1))

standard division 14.142135623730951


In [12]:
print("var",np.var(ar1))

var 200.0


In [14]:
#variance manually 
avg=np.mean(ar1)
ar2=ar1-avg
ar3=ar2**2
ar4=ar3.sum()
var_res=ar4/ar1.size
std_res=np.sqrt(var_res)
print("variance",var_res)
print("Standard division",std_res)

variance 200.0
Standard division 14.142135623730951


In [33]:
ar=np.array([    
    [1,2,3]
    ,[4,5,6]
    ])

ar.ndim


2

In [135]:
print("sum",np.shape(ar))

sum (2, 3)


In [34]:
ar.sum()

np.int64(21)

In [35]:
ar.mean()

np.float64(3.5)

In [40]:
ar.std()
# print(np.std(ar))

np.float64(1.707825127659933)

In [41]:
ar[1]

array([4, 5, 6])

In [43]:
ar[0]

array([1, 2, 3])

In [44]:
ar[1,0]

np.int64(4)

In [45]:
ar[1,2
   ]

np.int64(6)

In [48]:
ar[1].sum()/3


np.float64(5.0)

In [52]:
ar[1,1]

np.int64(5)

In [53]:
ar[0,1]-ar[1,2]

np.int64(-4)

In [54]:
ar[1]-ar[0]

array([3, 3, 3])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
ar.min()

np.int64(1)

In [60]:
ar.max()

np.int64(6)

In [ ]:
ar.var()

np.float64(2.9166666666666665)

In [65]:
print(np.max(ar[1]))

6


In [66]:
ar[1].max()

np.int64(6)

In [67]:
ar[0].max()

np.int64(3)

In [88]:
ar[0:1,0]

array([1])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
ar[0:1,1:3]

array([[2, 3]])

In [107]:
ar[1:2,0:2]

array([[4, 5]])

In [109]:
ar[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [110]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
ar[0:2,0:1]

array([[1],
       [4]])

In [117]:
ar[0:2,1:2]

array([[2],
       [5]])

In [115]:
ar[0:2,2:3]

array([[3],
       [6]])

In [119]:
ar[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
ar[0]

array([1, 2, 3])

In [127]:
ar[-1]

array([4, 5, 6])

In [133]:
ar[:,:1]

array([[1],
       [4]])

In [138]:
ar.shape[1]

3

In [141]:
ar.shape

(2, 3)

In [148]:
for i in range(ar.shape[0]):
    for j in range(ar.shape[1]):
        print(ar[i,j],end=" ")

1 2 3 4 5 6 

In [147]:
for i in ar:
    for j in i:
        print(j,end=" ")

1 2 3 4 5 6 

In [160]:
while i < ar.size:
    i+=1
    while j < ar.size:
        print(ar)
        j+=1



[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [163]:
ar.size

6