In [1]:
import numpy as np

In [2]:
l1=[10,20,30,40]
ar1=np.array(l1)

In [ ]:
#3d ke ander jitne 2d hoge vo sare block ki tarah consider hoge 

In [72]:
l3=[
    [ [ 10,20,30] , [20,30,40]],
    [ [40,20,30 ], [ 30,40,50]]
]

ar3=np.array(l3)

In [73]:
l4=[
    [ [40,20,50] , [20,60,40]],
    [ [90,20,80 ], [50,40,50]]
]

ar4=np.array(l4)

In [4]:
print(ar3)

[[[10 20 30]
  [20 30 40]]

 [[40 20 30]
  [30 40 50]]]


In [5]:
ar3.size

12

In [6]:
ar3.ndim

3

In [21]:
ar3.shape
# (a = block , b = row , c = column)

(2, 2, 3)

In [9]:
ar3.min()

np.int64(10)

In [10]:
ar3.max()

np.int64(50)

In [11]:
ar3.mean()

np.float64(30.0)

In [13]:
ar3.var()

np.float64(116.66666666666667)

In [14]:
#har 2d ke ander jitni bhi 1d hote hai unko row consider krna hota hai
ar3[0]

array([[10, 20, 30],
       [20, 30, 40]])

In [15]:
ar3[0,0]

array([10, 20, 30])

In [16]:
ar3[0,0,0
    ]

np.int64(10)

In [17]:
ar3[1,0,0]

np.int64(40)

In [19]:
ar3[1,0,2]

np.int64(30)

In [22]:
# array ka size equal hona chaiheye kuch bhi ho 

In [33]:
ar3[0][1].mean()

np.float64(30.0)

In [35]:
ar3[0][0].mean()

np.float64(20.0)

In [36]:
ar3

array([[[10, 20, 30],
        [20, 30, 40]],

       [[40, 20, 30],
        [30, 40, 50]]])

In [41]:
print(ar3[1,1,1],ar3[1,0,1])

40 20


### slicing


In [42]:
ar3

array([[[10, 20, 30],
        [20, 30, 40]],

       [[40, 20, 30],
        [30, 40, 50]]])

In [44]:
ar3[0:2,0:2,0:1]

array([[[10],
        [20]],

       [[40],
        [30]]])

In [48]:
for i in ar3:
    for j in i:
       for k in j:
           print(k,end=" ")
    #  print(j)

10 20 30 20 30 40 40 20 30 30 40 50 

In [50]:
ar3

array([[[10, 20, 30],
        [20, 30, 40]],

       [[40, 20, 30],
        [30, 40, 50]]])

In [55]:
for i in range(ar3.shape[0]):
    for j in range(ar3.shape[1]):
        for k in range(ar3.shape[2]):
            print(ar3[i,j,k],end=" ")

10 20 30 20 30 40 40 20 30 30 40 50 

In [56]:
ar1=ar3.flatten()

In [57]:
ar1

array([10, 20, 30, 20, 30, 40, 40, 20, 30, 30, 40, 50])

In [63]:
ar2=ar3.reshape(3,4)

In [65]:
ar2

array([[10, 20, 30, 20],
       [30, 40, 40, 20],
       [30, 30, 40, 50]])

In [66]:
ar3

array([[[10, 20, 30],
        [20, 30, 40]],

       [[40, 20, 30],
        [30, 40, 50]]])

In [67]:
ar3.size

12

In [69]:
ar2.reshape(2,2,3)

array([[[10, 20, 30],
        [20, 30, 40]],

       [[40, 20, 30],
        [30, 40, 50]]])

In [70]:
np.add
np.subtract
np.divide
np.multiply
np.floor

<ufunc 'floor'>

In [76]:
np.add(ar3,ar4)

array([[[ 50,  40,  80],
        [ 40,  90,  80]],

       [[130,  40, 110],
        [ 80,  80, 100]]])

In [77]:
np.subtract(ar3,ar4
            )

array([[[-30,   0, -20],
        [  0, -30,   0]],

       [[-50,   0, -50],
        [-20,   0,   0]]])

In [78]:
np.multiply(ar3,ar4)

array([[[ 400,  400, 1500],
        [ 400, 1800, 1600]],

       [[3600,  400, 2400],
        [1500, 1600, 2500]]])

In [ ]:
np.divide(ar3,ar4
          )

array([[[0.25      , 1.        , 0.6       ],
        [1.        , 0.5       , 1.        ]],

       [[0.44444444, 1.        , 0.375     ],
        [0.6       , 1.        , 1.        ]]])

In [80]:
np.floor(ar3,ar4)

array([[[10, 20, 30],
        [20, 30, 40]],

       [[40, 20, 30],
        [30, 40, 50]]])

In [82]:
np.vecdot(ar3,ar4)

array([[1400, 2900],
       [2900, 5000]])